//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Myproto.proto
namespace Myproto
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"MsgRequest")]
    public partial class MsgRequest : global::ProtoBuf.IExtensible
    {
        public MsgRequest() { }

        private string _id;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string id
        {
            get { return _id; }
            set { _id = value; }
        }
        private Content _content;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Content content
        {
            get { return _content; }
            set { _content = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"MsgResponse")]
    public partial class MsgResponse : global::ProtoBuf.IExtensible
    {
        public MsgResponse() { }

        private string _id;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string id
        {
            get { return _id; }
            set { _id = value; }
        }
        private Content _content;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Content content
        {
            get { return _content; }
            set { _content = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Content")]
    public partial class Content : global::ProtoBuf.IExtensible
    {
        public Content() { }

        private readonly global::System.Collections.Generic.List<Msg> _msg = new global::System.Collections.Generic.List<Msg>();
        [global::ProtoBuf.ProtoMember(1, Name = @"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Msg> msg
        {
            get { return _msg; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Msg")]
    public partial class Msg : global::ProtoBuf.IExtensible
    {
        public Msg() { }

        private MsgType _type;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public MsgType type
        {
            get { return _type; }
            set { _type = value; }
        }
        private string _id = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string id
        {
            get { return _id; }
            set { _id = value; }
        }
        private byte[] _body;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"body", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public byte[] body
        {
            get { return _body; }
            set { _body = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::ProtoBuf.ProtoContract(Name = @"MsgType")]
    public enum MsgType
    {

        [global::ProtoBuf.ProtoEnum(Name = @"AssetLoad", Value = 1)]
        AssetLoad = 1,

        [global::ProtoBuf.ProtoEnum(Name = @"GameObjectAdd", Value = 2)]
        GameObjectAdd = 2,

        [global::ProtoBuf.ProtoEnum(Name = @"GameObjectRemove", Value = 3)]
        GameObjectRemove = 3,

        [global::ProtoBuf.ProtoEnum(Name = @"UserEvent", Value = 4)]
        UserEvent = 4,

        [global::ProtoBuf.ProtoEnum(Name = @"AssetUpload", Value = 5)]
        AssetUpload = 5
    }

}
